# utility job used to help with debugging database
# and other issues
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fire-data-acquisition-job
spec:
  #ttlSecondsAfterFinished: 100
  suspend: true
  schedule: "5 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: firedata-volume
            persistentVolumeClaim:
              claimName: {{ .Values.fire_data_job.fire_data_pvc_name }}
          containers:
          - name: firedata
            image: >-
              {{ .Values.image.registry }}/{{ .Values.image.promote }}

            volumeMounts:
            - name: firedata-volume
              mountPath: {{ .Values.fire_data_job.fire_data_mnt_point }}

            #Calling the shell script that was pulled by the init container
            # link to article showing how to call multiple commands in single
            # call: https://stackoverflow.com/questions/33979501/kubernetes-passing-multiple-commands-to-the-container
            # --- lines to add back into the command args..
            # python main_fwx.py &&
            command: ["/bin/bash"]
            args:
              - -c
              - >-
                  python main_fwx.py &&
                  echo running the r script &&
                  mkdir -p /data/renvcache &&
                  Rscript hourly_format.R
            env:
              - name: OBJ_STORE_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: OBJ_STORE_BUCKET
                    name: {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.obj_store.secret_name }}
              - name: OBJ_STORE_HOST
                valueFrom:
                  secretKeyRef:
                    key: OBJ_STORE_HOST
                    name: {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.obj_store.secret_name }}
              - name: OBJ_STORE_USER
                valueFrom:
                  secretKeyRef:
                    key: OBJ_STORE_USER
                    name: {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.obj_store.secret_name }}
              - name: OBJ_STORE_SECRET
                valueFrom:
                  secretKeyRef:
                    key: OBJ_STORE_SECRET
                    name: {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.obj_store.secret_name }}
              - name: F_WX_DATA_DIR
                value: {{ .Values.fire_data_job.fire_data_mnt_point }}
              - name: RENV_PATHS_ROOT
                value: /data/renvcache
          restartPolicy: Never
