apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.app.name }}-{{ .Values.app.zone }}-{{ .Values.obj_store.secret_name }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.zone }}
stringData:
  OBJ_STORE_BUCKET: {{ .Values.obj_store.bucket }}
  OBJ_STORE_HOST: {{ .Values.obj_store.host }}
  OBJ_STORE_USER: {{ .Values.obj_store.user_id }}
  OBJ_STORE_SECRET: {{ .Values.obj_store.secret }}
