name: Download and process hourly weather obs from datamart

on:
  # push:
  #   branches:
  #     - "main"
  schedule:
  # job should run at 9.01 pst which translates to 5pm UTC
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  download_datamart_climateobs:
    defaults:
      run:
        shell: bash
    name: 'Download and process hourly datamart weather observations'
    runs-on: ubuntu-20.04
    environment: PROD
    env:
      OBJ_STORE_BUCKET: ${{ secrets.OBJ_STORE_BUCKET }}
      OBJ_STORE_SECRET: ${{ secrets.OBJ_STORE_SECRET }}
      OBJ_STORE_USER: ${{ secrets.OBJ_STORE_USER }}
      OBJ_STORE_HOST: ${{ vars.OBJ_STORE_HOST }}

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
       fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - id: install_dependencies
      name: install python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r scripts/python/requirements-datamartdl.txt

    - id: debug
      name: debug and list files
      shell: bash
      run: |
        ls -la

    - id: download_DataMart
      name: download datamart climateobs data and upload to s3
      shell: bash
      run: |
        python scripts/python/DataMart_hourly_download.py
